### ISSUE TITLE
Tests are not passing.

### ISSUE THREAD

**Issue by alonsoir** [alonsoir/demoFaceRecognition#1]
`[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.67 s <<< FAILURE! - in com.aironman.demoFaceRecognition.DemoFaceRecognitionApplicationTests
**[ERROR] loadPhotoIntoModel(com.aironman.demoFaceRecognition.DemoFaceRecognitionApplicationTests)  Time elapsed: 0.051 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
        at com.aironman.demoFaceRecognition.DemoFaceRecognitionApplicationTests.loadPhotoIntoModel(DemoFaceRecognitionApplicationTests.java:33)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc in java.library.path
        at com.aironman.demoFaceRecognition.DemoFaceRecognitionApplicationTests.loadPhotoIntoModel(DemoFaceRecognitionApplicationTests.java:33)

[ERROR] loadModel(com.aironman.demoFaceRecognition.DemoFaceRecognitionApplicationTests)  Time elapsed: 2.336 s  <<< ERROR!
java.lang.IllegalStateException: Illegal set of indices for array: need at least 1 point/interval/all/specified indices for rank 1 array ([9472]), got indices [Point(0), Interval(b=0,e=64,s=1)]**
        at com.aironman.demoFaceRecognition.DemoFaceRecognitionApplicationTests.loadModel(DemoFaceRecognitionApplicationTests.java:26)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DemoFaceRecognitionApplicationTests.loadModel:26 » IllegalState Illegal set of...
[ERROR]   DemoFaceRecognitionApplicationTests.loadPhotoIntoModel:33 » UnsatisfiedLink no...
[INFO] 
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
`

**Comment by alonsoir** [comment]
After speaking with Klevis, I understand that it is not a good idea to create the model from cvs files. The best thing is to import keras pretained model, which implies that I have to change code, dependencies ...

"Anyway one thing I can suggest is to import the model from Keras instead of reading weights from xls.
I remember  I did this some time ago and it worked fine(in this case probably the version will be OK to since dl4j are testing import operations).
"
